+---------------------+
| @ dungeon main      |
|                     |
|  gold x = 40        |
|  gold y = 12        |
|  gold dx = 1        |
|  gold dy = 1        |
|                     |
|  wander(true) {     |
|    scribe(x, y, 32) |
|    x += dx          |
|    y += dy          |
|                     |
|    ? (78 < x) {     |
|      dx = 0 - 1     |
|    }                |
|    ? (x < 1) {      |
|      dx = 1         |
|    }                |
|    ? (23 < y) {     |
|      dy = 0 - 1     |
|    }                |
|    ? (y < 1) {      |
|      dy = 1         |
|    }                |
|                     |
|    scribe(x, y, 79) |
|    reveal()         |
|  }                  |
|                     |
|  > 0                |
+---------------------+